name: Deploy PROD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/974898737307/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deploy-notification@travelhub-prod-492116.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - name: Deploy
        run: bash deploy/deploy-prod.sh
        env:
          GCP_PROJECT_ID: travelhub-prod-492116
